---
- name: Create a new server instance in AWS EC2 if none exist with tag "{{ simplye_role }}-{{ simplye_instance_name }}"
  local_action:
    module: ec2
    wait: yes
    wait_timeout: 600
    region: "{{ aws_region }}"
    instance_type: "{{ ec2_instance_type }}"
    exact_count: 1
    count_tag:
      Name: "{{ simplye_role }}-{{ simplye_instance_name }}"
    instance_tags: '{"Name":"{{ simplye_role }}-{{ simplye_instance_name }}","Type":"{{ simplye_role }}","Environment":"{{ simplye_environment }}"}'
    key_name: "{{ simplye_instance_name }}"
    group_id: "{{ ec2_sg.group_id }}"
    image: "{{ ec2_image }}"
    vpc_subnet_id: "{{ ec2_subnet_ids|random }}"
    assign_public_ip: yes
    volumes:
    - device_name: /dev/xvda
      device_type: gp2
      volume_size: "{{ ec2_volume_size }}"
      delete_on_termination: true
  register: ec2

- debug: var=item
  with_items: "{{ ec2.instances }}"

- name: Add instance to host group in working memory
  add_host: hostname="{{ item.public_ip }}" groupname="{{ simplye_role }}-servers" ansible_ssh_private_key_file="~/.ssh/{{ simplye_instance_name }}.pem"
  with_items:
    - "{{ ec2.instances }}"
    - "{{ ec2.tagged_instances }}"

- name: Check SSH to make sure the instance boots
  wait_for: host={{ item.public_ip }} port=22 delay=60 timeout=320 state=started
  with_items: "{{ ec2.instances }}"

- name: Add instance IPs as playbook facts
  set_fact:
    ec2_ip: "{{ item.public_ip }}"
    ec2_private_ip: "{{ item.private_ip }}"
  with_items:
    - "{{ ec2.instances }}"
    - "{{ ec2.tagged_instances }}"

- debug: var=ec2_private_ip
